# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07f7ddd6-89ad-4a29-8c7c-609f32a6aabd";
      fsType = "ext4";
    };

  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/9575-3AA2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" = {
      device = "/dev/disk/by-uuid/a44fb9b2-bd12-4db7-abc6-5c46d2302557";
      fsType = "ext4";
    };
    fileSystems."/mnt/windows/E" = {
      device = "/dev/disk/by-uuid/A2806E4D806E284D";
      fsType = "ntfs-3g";
      options = [
        "rw"
        "uid=1000"
        "gid=100"
        "noauto"
        "nofail"
        "x-systemd.automount"
      ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
}
