[
  "no_blur on, match:class ^(\bresolve\b)$, match:xwayland 1"
  "tag +file-manager, match:class ^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$"
  "tag +terminal, match:class ^(foot|kitty)$"
  "tag +browser, match:class ^(Brave-browser(-beta|-dev|-unstable)?)$"
  "tag +browser, match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$"
  "tag +browser, match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$"
  "tag +browser, match:class ^([Tt]horium-browser|[Cc]achy-browser)$"
  "tag +projects, match:class ^(codium|codium-url-handler|VSCodium)$"
  "tag +projects, match:class ^(VSCode|code-url-handler)$"
  "tag +im, match:class ^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$"
  "tag +im, center on, float on, size (monitor_w*0.6) (monitor_h*0.7), match:class ^([Ff]erdium)$"
  "tag +im, match:class ^([Ww]hatsapp-for-linux)$"
  "tag +im, match:class ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"
  "tag +im, match:class ^(teams-for-linux)$"
  "tag +settings, match:class ^(gnome-disks|wihotspot(-gui)?)$"
  "tag +settings, match:class ^([Rr]ofi)$"
  "tag +settings, match:class ^(file-roller|org.gnome.FileRoller)$"
  "tag +settings, match:class ^(nm-applet|nm-connection-editor|blueman-manager)$"
  "tag +settings, center on, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
  "tag +settings, match:class ^(nwg-look|qt5ct|qt6ct|[Yy]ad)$"
  "tag +settings, match:class (xdg-desktop-portal-gtk)"
  "tag +settings, match:class (.blueman-manager-wrapped)"
  "tag +settings, match:class (nwg-displays)"
  "float on, match:class ^([Ww]aypaper)$"
  "center on, float on, match:class ([Tt]hunar), match:title negative:(.*[Tt]hunar.*)"
  "center on, float on, match:title ^(Authentication Required)$"
  "idle_inhibit fullscreen, suppress_event maximize, match:class .*"
  "idle_inhibit fullscreen, match:title .*"
  "idle_inhibit fullscreen, match:fullscreen 1"
  "float on, size (monitor_w*0.7) (monitor_h*0.7), opacity 0.8 0.7, match:tag settings*"
  "float on, match:class ^(mpv|com.github.rafostar.Clapper)$"
  "float on, match:class (codium|codium-url-handler|VSCodium), match:title negative:(.*codium.*|.*VSCodium.*)"
  "float on, match:class ^([Ss]team)$, match:title negative:^([Ss]team)$"
  "float on, size (monitor_w*0.7) (monitor_h*0.6), match:initial_title (Add Folder to Workspace)"
  "float on, size (monitor_w*0.7) (monitor_h*0.6), match:initial_title (Open Files)"
  "float on, match:initial_title (wants to save)"
  "opacity 1.0 1.0, match:tag browser*"
  "opacity 0.9 0.8, match:tag projects*"
  "opacity 0.94 0.86, match:tag im*"
  "opacity 0.9 0.8, match:tag file-manager*"
  "opacity 0.9 0.7, match:tag terminal*"
  "opacity 0.8 0.7, match:class ^(gedit|org.gnome.TextEditor|mousepad)$"
  "opacity 0.9 0.8, match:class ^(seahorse)$ # gnome-keyring gui"
  "no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0"
]
